(function(){
  'use strict';
  if (window.BwindWebLab) return;
  var rootId='bwind-weblab-root', styleId='bwind-weblab-style';
  var active=false, selecting=false, selected=null, snapshots=[], redo=[], originalBody='';
  var presetKey='bwind-weblab-preset:'+location.origin+location.pathname;
  function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c];});}
  function css(){if(document.getElementById(styleId))return;var s=document.createElement('style');s.id=styleId;s.textContent='@keyframes bwind-wl-shake{0%,100%{transform:translate(0,0) rotate(0)}20%{transform:translate(-5px,3px) rotate(-1deg)}40%{transform:translate(4px,-4px) rotate(1deg)}60%{transform:translate(-3px,-2px) rotate(0)}80%{transform:translate(5px,3px) rotate(1deg)}}@keyframes bwind-wl-float{0%,100%{transform:translateY(0)}50%{transform:translateY(-12px)}}.bwind-wl-shake>*:not(#'+rootId+'){animation:bwind-wl-shake .22s infinite}.bwind-wl-float{animation:bwind-wl-float 2s ease-in-out infinite!important}.bwind-wl-particle{position:fixed!important;width:8px!important;height:8px!important;border-radius:50%!important;background:#47d7ff!important;box-shadow:0 0 12px #47d7ff!important;z-index:2147483645!important;pointer-events:none!important;animation:bwind-wl-particle 2.5s linear infinite!important}@keyframes bwind-wl-particle{from{transform:translateY(0) scale(1);opacity:1}to{transform:translateY(100vh) scale(.2);opacity:0}}';document.documentElement.appendChild(s)}
  function snap(){var c=document.body.cloneNode(true),r=c.querySelector('#'+rootId);if(r)r.remove();snapshots.push(c.innerHTML);if(snapshots.length>20)snapshots.shift();redo=[]}
  function status(t){var e=document.getElementById('bwind-wl-status');if(e)e.textContent=t}
  function selectedLabel(){return selected?(selected.tagName.toLowerCase()+(selected.id?'#'+selected.id:'')): 'nenhum elemento selecionado'}
  function pick(e){if(!selecting||e.target.closest('#'+rootId))return;e.preventDefault();e.stopPropagation();if(selected)selected.style.outline='';selected=e.target;selected.style.outline='3px solid #47d7ff';selecting=false;status('Selecionado: '+selectedLabel())}
  function button(label,fn){var b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=function(e){e.stopPropagation();fn()};return b}
  function mount(){css();var old=document.getElementById(rootId);if(old)old.remove();var r=document.createElement('div');r.id=rootId;r.style.cssText='position:fixed;left:10px;right:10px;bottom:12px;z-index:2147483646;background:#10182a;color:#eaf3ff;border:1px solid #47d7ff;border-radius:14px;padding:10px;font:13px sans-serif;box-shadow:0 8px 30px #0008';var h=document.createElement('div');h.style.cssText='display:flex;align-items:center;gap:8px;margin-bottom:7px';var title=document.createElement('b');title.textContent='🧪 WebLab';title.style.cssText='font-size:16px;color:#47d7ff';h.appendChild(title);var st=document.createElement('span');st.id='bwind-wl-status';st.textContent='Escolha Selecionar para editar a página';st.style.cssText='flex:1;color:#b6c7d9;font-size:11px';h.appendChild(st);h.appendChild(button('Sair',exit));r.appendChild(h);var tools=document.createElement('div');tools.style.cssText='display:flex;flex-wrap:wrap;gap:5px;max-height:145px;overflow:auto';tools.appendChild(button('Selecionar',function(){selecting=true;status('Toque em qualquer elemento da página')}));tools.appendChild(button('Duplicar',duplicate));tools.appendChild(button('Texto',changeText));tools.appendChild(button('Imagem',changeImage));tools.appendChild(button('Cor',changeColor));tools.appendChild(button('Flutuar',floatSelected));tools.appendChild(button('Terremoto',shake));tools.appendChild(button('Partículas',particles));tools.appendChild(button('Desfazer',undo));tools.appendChild(button('Refazer',redoAction));tools.appendChild(button('Restaurar',restore));tools.appendChild(button('Salvar preset',savePreset));tools.appendChild(button('Carregar preset',loadPreset));r.appendChild(tools);document.documentElement.appendChild(r);document.addEventListener('click',pick,true)}
  function requireSelected(){if(!selected||!document.body.contains(selected)){status('Selecione um elemento primeiro');return false}return true}
  function duplicate(){if(!requireSelected())return;snap();var c=selected.cloneNode(true);selected.parentNode.insertBefore(c,selected.nextSibling);selected=c;selected.style.outline='3px solid #47d7ff';status('Elemento duplicado')}
  function changeText(){if(!requireSelected())return;var v=prompt('Novo texto visual:',selected.innerText||selected.textContent||'');if(v===null)return;snap();if('value'in selected)selected.value=v;else selected.textContent=v;status('Texto alterado visualmente')}
  function changeImage(){if(!requireSelected())return;var img=selected.tagName==='IMG'?selected:selected.querySelector('img');var v=prompt('URL da nova imagem:',img?img.src:'');if(v===null||!v.trim())return;snap();if(img)img.src=v;else selected.style.backgroundImage='url("'+v.replace(/\"/g,'')+'")';status('Imagem alterada visualmente')}
  function changeColor(){if(!requireSelected())return;var v=prompt('Cor CSS (ex.: #ff4d8d ou yellow):',selected.style.color||'#47d7ff');if(v===null||!v.trim())return;snap();selected.style.color=v;selected.style.borderColor=v;status('Cor alterada')}
  function floatSelected(){if(!requireSelected())return;snap();selected.classList.toggle('bwind-wl-float');selected.style.position=selected.classList.contains('bwind-wl-float')?'relative':'';status('Flutuação alternada')}
  function shake(){snap();document.body.classList.toggle('bwind-wl-shake');status('Efeito terremoto alternado')}
  function particles(){for(var i=0;i<24;i++){var p=document.createElement('i');p.className='bwind-wl-particle';p.style.left=(Math.random()*100)+'vw';p.style.top=(Math.random()*35)+'vh';p.style.animationDelay=(Math.random()*2)+'s';document.body.appendChild(p)}status('Partículas adicionadas; use Restaurar para remover')}
  function restore(){if(!originalBody)return;snapshots.push(document.body.innerHTML);document.body.innerHTML=originalBody;selected=null;mount();status('Página restaurada ao estado inicial')}
  function undo(){if(!snapshots.length){status('Nada para desfazer');return}var c=document.body.cloneNode(true),r=c.querySelector('#'+rootId);if(r)r.remove();redo.push(c.innerHTML);var html=snapshots.pop();document.body.innerHTML=html;selected=null;mount();status('Ação desfeita')}
  function redoAction(){if(!redo.length){status('Nada para refazer');return}var c=document.body.cloneNode(true),r=c.querySelector('#'+rootId);if(r)r.remove();snapshots.push(c.innerHTML);var html=redo.pop();document.body.innerHTML=html;selected=null;mount();status('Ação refeita')}
  function savePreset(){var c=document.body.cloneNode(true),r=c.querySelector('#'+rootId);if(r)r.remove();localStorage.setItem(presetKey,c.innerHTML);status('Preset salvo neste site')}
  function loadPreset(){var html=localStorage.getItem(presetKey);if(!html){status('Nenhum preset salvo para esta página');return}snapshots.push(document.body.innerHTML);document.body.innerHTML=html;selected=null;mount();status('Preset carregado')}
  function start(){if(active)return;active=true;var c=document.body.cloneNode(true),r=c.querySelector('#'+rootId);if(r)r.remove();originalBody=c.innerHTML;snapshots=[];redo=[];mount()}
  function exit(){var r=document.getElementById(rootId);if(r)r.remove();document.removeEventListener('click',pick,true);if(selected)selected.style.outline='';document.body.classList.remove('bwind-wl-shake');document.querySelectorAll('.bwind-wl-particle').forEach(function(e){e.remove()});var s=document.getElementById(styleId);if(s)s.remove();active=false;selected=null}
  window.BwindWebLab={toggle:function(){active?exit():start()},start:start,exit:exit,restore:restore};
})();
