(function(){
  'use strict';
  if(window.BwindWebArcade)return;
  var id='bwind-web-arcade-root',active=false,mode='clicker',score=0,time=0,raf=0,timer=0,objects=[],customModes=[];
  try{customModes=JSON.parse(localStorage.getItem('bwind-arcade-modes')||'[]')}catch(e){customModes=[]}
  function css(){if(document.getElementById(id+'-style'))return;var s=document.createElement('style');s.id=id+'-style';s.textContent='@keyframes bwind-arcade-pop{0%{transform:scale(.7);opacity:.2}60%{transform:scale(1.15);opacity:1}100%{transform:scale(1);opacity:1}}@keyframes bwind-arcade-glow{0%,100%{box-shadow:0 0 5px #ffc857}50%{box-shadow:0 0 22px #ffc857}}.bwind-arcade-coin{position:fixed;width:34px;height:34px;border-radius:50%;background:#ffc857;color:#5b3b00;border:2px solid #fff0a8;font:bold 16px sans-serif;z-index:2147483644;display:flex;align-items:center;justify-content:center;cursor:pointer;animation:bwind-arcade-pop .25s,bwind-arcade-glow 1s infinite}.bwind-arcade-enemy{position:fixed;width:38px;height:38px;background:#ff466f;color:white;border:2px solid #ffb1c0;clip-path:polygon(50% 0,62% 28%,100% 26%,74% 52%,84% 100%,50% 72%,16% 100%,26% 52%,0 26%,38% 28%);z-index:2147483644;cursor:pointer;animation:bwind-arcade-pop .25s}.bwind-arcade-block{position:fixed;width:30px;height:30px;border-radius:7px;background:#47d7ff;z-index:2147483643;pointer-events:none;opacity:.9}';document.documentElement.appendChild(s)}
  function el(tag,text){var e=document.createElement(tag);if(text!=null)e.textContent=text;return e}
  function button(text,fn){var b=el('button',text);b.type='button';b.onclick=function(e){e.stopPropagation();fn()};return b}
  function modeName(m){return m==='clicker'?'CLICKER':m==='chaos'?'WEB CHAOS':m==='coins'?'COIN HUNT':m==='invasion'?'INVASÃO':m.toUpperCase()}
  function setStatus(t){var e=document.getElementById('bwind-arcade-status');if(e)e.textContent=t}
  function updateHud(){var s=document.getElementById('bwind-arcade-score');if(s)s.textContent='Pontos: '+score;var t=document.getElementById('bwind-arcade-time');if(t)t.textContent='Tempo: '+time+'s'}
  function mount(){css();var old=document.getElementById(id);if(old)old.remove();var r=el('div');r.id=id;r.style.cssText='position:fixed;inset:0;z-index:2147483642;pointer-events:none;font:13px sans-serif;color:#eaf3ff';var hud=el('div');hud.style.cssText='pointer-events:auto;position:fixed;top:12px;left:12px;right:12px;background:#10182aee;border:1px solid #47d7ff;border-radius:15px;padding:10px;box-shadow:0 8px 32px #0009';var line=el('div');line.style.cssText='display:flex;align-items:center;gap:8px';var title=el('b','🎮 WEB ARCADE');title.style.cssText='font-size:16px;color:#47d7ff;flex:1';line.appendChild(title);var sc=el('span');sc.id='bwind-arcade-score';line.appendChild(sc);var tm=el('span');tm.id='bwind-arcade-time';line.appendChild(tm);line.appendChild(button('Sair',exit));hud.appendChild(line);var modes=el('div');modes.style.cssText='display:flex;gap:4px;flex-wrap:wrap;margin-top:8px';['clicker','chaos','coins','invasion'].concat(customModes.map(function(x){return x.name})).forEach(function(m){var b=button(modeName(m),function(){startMode(m)});b.style.fontSize='11px';modes.appendChild(b)});modes.appendChild(button('+ Criar modo',createMode));hud.appendChild(modes);var st=el('div','Clique nos elementos ou escolha um modo para começar');st.id='bwind-arcade-status';st.style.cssText='color:#a9bed3;font-size:11px;margin-top:6px';hud.appendChild(st);r.appendChild(hud);document.documentElement.appendChild(r);updateHud()}
  function clearObjects(){objects.forEach(function(o){if(o.el)o.el.remove()});objects=[];if(raf)cancelAnimationFrame(raf);raf=0}
  function startMode(m){clearObjects();score=0;time=m==='clicker'?0:30;mode=m;updateHud();setStatus('Modo '+modeName(m)+' iniciado');if(m==='clicker')startClicker();else if(m==='chaos')startChaos();else if(m==='coins')startCoins();else if(m==='invasion')startInvasion();else{var found=customModes.find(function(x){return x.name===m});startType(found?found.type:'clicker')}if(m!=='clicker')startTimer()}
  function startType(t){if(t==='chaos')startChaos();else if(t==='coins')startCoins();else if(t==='invasion')startInvasion();else startClicker()}
  function startClicker(){document.addEventListener('click',clickPage,true)}
  function clickPage(e){if(!active||mode!=='clicker'||e.target.closest('#'+id))return;score++;updateHud();setStatus('Clique! Pontos: '+score)}
  function startTimer(){clearInterval(timer);timer=setInterval(function(){if(!active)return;time--;updateHud();if(time<=0){clearInterval(timer);setStatus('Tempo acabou! Pontuação: '+score);clearObjects()}},1000)}
  function randPos(){return {x:Math.max(4,Math.random()*88),y:Math.max(12,Math.random()*70)}}
  function spawnCoin(enemy){var o={el:el('button',enemy?'✦':'¢'),x:randPos().x,y:randPos().y,enemy:enemy};o.el.className=enemy?'bwind-arcade-enemy':'bwind-arcade-coin';o.el.style.left=o.x+'vw';o.el.style.top=o.y+'vh';o.el.onclick=function(e){e.stopPropagation();score+=enemy?5:1;updateHud();o.el.remove();objects=objects.filter(function(v){return v!==o});setStatus(enemy?'Inimigo atingido! +5':'Moeda coletada! +1')};document.documentElement.appendChild(o.el);objects.push(o)}
  function startCoins(){for(var i=0;i<6;i++)spawnCoin(false);var add=setInterval(function(){if(!active||mode!=='coins'){clearInterval(add);return}if(objects.length<12)spawnCoin(false)},1200);objects.push({interval:add})}
  function startInvasion(){for(var i=0;i<4;i++)spawnCoin(true);var add=setInterval(function(){if(!active||mode!=='invasion'){clearInterval(add);return}if(objects.filter(function(o){return o.enemy}).length<10)spawnCoin(true)},1500);objects.push({interval:add})}
  function startChaos(){for(var i=0;i<18;i++){var o={el:el('div'),x:Math.random()*96,y:-Math.random()*100,vy:1+Math.random()*2,vx:(Math.random()-.5)*.7};o.el.className='bwind-arcade-block';o.el.style.left=o.x+'vw';o.el.style.top=o.y+'vh';document.documentElement.appendChild(o.el);objects.push(o)}var last=performance.now();function frame(now){if(!active||mode!=='chaos')return;var dt=Math.min(3,(now-last)/16);last=now;objects.forEach(function(o){if(!o.el)return;o.y+=o.vy*dt;o.x+=o.vx*dt;if(o.y>105)o.y=-8;if(o.x<0||o.x>98)o.vx*=-1;o.el.style.left=o.x+'vw';o.el.style.top=o.y+'vh'});raf=requestAnimationFrame(frame)}raf=requestAnimationFrame(frame);setStatus('Objetos caindo pela página; troque de modo ou saia para encerrar')}
  function createMode(){var name=prompt('Nome do seu modo:');if(!name||!name.trim())return;var type=prompt('Tipo: clicker, chaos, coins ou invasion','clicker');type=(type||'clicker').toLowerCase();if(['clicker','chaos','coins','invasion'].indexOf(type)<0)type='clicker';customModes.push({name:name.trim().slice(0,20),type:type});localStorage.setItem('bwind-arcade-modes',JSON.stringify(customModes));mount();setStatus('Modo '+name.trim()+' criado e salvo neste site')}
  function exit(){clearInterval(timer);timer=0;document.removeEventListener('click',clickPage,true);clearObjects();var r=document.getElementById(id);if(r)r.remove();var s=document.getElementById(id+'-style');if(s)s.remove();active=false}
  function start(){if(active)return;active=true;mount();startMode('clicker')}
  window.BwindWebArcade={toggle:function(){active?exit():start()},start:start,exit:exit};
  document.addEventListener('keydown',function(e){if(active&&e.key==='Escape')exit()});
})();
