(function(){
  'use strict';
  if(window.BwindSiteDetective)return;
  var id='bwind-site-detective-root',active=false;
  function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
  function detect(){
    var resources=performance.getEntriesByType?performance.getEntriesByType('resource'):[], scripts=document.scripts||[], links=document.links||[], imgs=document.images||[], styles=document.styleSheets||[], forms=document.forms||[], iframes=document.querySelectorAll('iframe'), els=document.querySelectorAll('*');
    var tech=[];
    if(window.React||document.querySelector('[data-reactroot],#__next'))tech.push('React');
    if(window.Vue||document.querySelector('[data-v-app],#__vue'))tech.push('Vue');
    if(window.angular||document.querySelector('[ng-version]'))tech.push('Angular');
    if(window.jQuery||window.$&&window.$.fn&&window.$.fn.jquery)tech.push('jQuery');
    if(document.querySelector('[class*="tailwind"], [class*="tw-"]'))tech.push('Tailwind provável');
    if(!tech.length){for(var i=0;i<scripts.length;i++){var src=scripts[i].src||'';if(/bootstrap/i.test(src))tech.push('Bootstrap');if(/tailwind/i.test(src))tech.push('Tailwind');if(/next/i.test(src))tech.push('Next.js')}}
    tech=[...new Set(tech)];
    var cookieCount=document.cookie?document.cookie.split(';').filter(Boolean).length:0;
    var perf=resources.map(function(r){return r.name}).filter(Boolean).slice(-120);
    return {url:location.href,title:document.title||'Sem título',domain:location.hostname||'Página local',technology:tech.length?tech.join(', '):'Não identificada',scripts:scripts.length,images:imgs.length,links:links.length,styles:styles.length,forms:forms.length,iframes:iframes.length,elements:els.length,cookies:cookieCount,requests:perf.length,requestList:perf,responsive:document.documentElement.clientWidth<=window.innerWidth+2?'SIM':'NÃO',viewport:window.innerWidth+' × '+window.innerHeight,secure:location.protocol==='https:'?'HTTPS':'Não HTTPS',updated:new Date().toLocaleTimeString()}
  }
  function report(d){return 'SITE DETECTIVE\n================\nTítulo: '+d.title+'\nEndereço: '+d.url+'\nDomínio: '+d.domain+'\nTecnologia: '+d.technology+'\nScripts: '+d.scripts+'\nImagens: '+d.images+'\nLinks: '+d.links+'\nFolhas de estilo: '+d.styles+'\nFormulários: '+d.forms+'\nIframes: '+d.iframes+'\nElementos: '+d.elements+'\nCookies acessíveis: '+d.cookies+'\nRequisições observáveis: '+d.requests+'\nResponsivo: '+d.responsive+'\nViewport: '+d.viewport+'\nSegurança: '+d.secure+'\nAtualizado: '+d.updated+'\n\nObservação: requisições e cookies podem ser parciais por limitações de segurança do navegador.'}
  function copy(t){if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(t).then(function(){var s=document.getElementById('bwind-sd-status');if(s)s.textContent='Relatório copiado'})}else{var a=document.createElement('textarea');a.value=t;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove();var s=document.getElementById('bwind-sd-status');if(s)s.textContent='Relatório copiado'}}
  function render(){var old=document.getElementById(id);if(old)old.remove();var d=detect(),r=document.createElement('aside');r.id=id;r.style.cssText='position:fixed;top:12px;right:12px;width:min(360px,calc(100vw - 24px));max-height:calc(100vh - 24px);overflow:auto;z-index:2147483646;background:#0c1424;color:#eaf3ff;border:1px solid #47d7ff;border-radius:16px;padding:14px;font:13px sans-serif;box-shadow:0 10px 36px #000b';var h=document.createElement('div');h.style.cssText='display:flex;align-items:center;gap:8px;margin-bottom:10px';var title=document.createElement('b');title.textContent='🕵️ SITE DETECTIVE';title.style.cssText='color:#47d7ff;font-size:16px;flex:1';h.appendChild(title);var close=document.createElement('button');close.textContent='×';close.onclick=exit;h.appendChild(close);r.appendChild(h);var data=[['Tecnologia',d.technology],['Scripts',d.scripts],['Imagens',d.images],['Links',d.links],['CSS',d.styles],['Formulários',d.forms],['Iframes',d.iframes],['Elementos',d.elements],['Cookies',d.cookies],['Requisições',d.requests],['Responsivo',d.responsive],['Segurança',d.secure]];var grid=document.createElement('div');grid.style.cssText='display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-bottom:10px';data.forEach(function(row){var box=document.createElement('div');box.style.cssText='background:#16243a;border-radius:9px;padding:8px';box.innerHTML='<small style="color:#a9bed3">'+esc(row[0])+'</small><br><b>'+esc(row[1])+'</b>';grid.appendChild(box)});r.appendChild(grid);var url=document.createElement('div');url.style.cssText='font-size:11px;color:#a9bed3;word-break:break-all;margin-bottom:8px';url.textContent=d.title+' — '+d.domain;r.appendChild(url);var actions=document.createElement('div');actions.style.cssText='display:flex;gap:6px';var refresh=document.createElement('button');refresh.textContent='Atualizar';refresh.onclick=render;var cp=document.createElement('button');cp.textContent='Copiar relatório';cp.onclick=function(){copy(report(d))};actions.appendChild(refresh);actions.appendChild(cp);r.appendChild(actions);var status=document.createElement('div');status.id='bwind-sd-status';status.style.cssText='color:#8de8ff;font-size:11px;margin-top:8px';status.textContent='Dados observáveis da página atual';r.appendChild(status);document.documentElement.appendChild(r)}
  function start(){if(active)return;active=true;render()}
  function exit(){var r=document.getElementById(id);if(r)r.remove();active=false}
  window.BwindSiteDetective={toggle:function(){active?exit():start()},start:start,exit:exit,refresh:render};
})();
